/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab11 */

#ifndef _Included_Lab11
#define _Included_Lab11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lab11
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Lab11_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     Lab11
 * Method:    isPrime
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Lab11_isPrime
  (JNIEnv *, jobject, jint);

/*
 * Class:     Lab11
 * Method:    forEachElement
 * Signature: ([FFLjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_Lab11_forEachElement
  (JNIEnv *, jobject, jfloatArray, jfloat, jstring);

#ifdef __cplusplus
}
#endif
#endif
